The problem solve here is to classify grayscale images of hand written digits (28 × 28 pixels) into their 10 categories
(0 through 9) using the MNIST dataset. It’s a set of 60,000 training images, plus 10,000 test images, assembled by the 
National Institute of Standards and Technology


2.2. The network architecture 
The core building block of neural networks is the layer,  a data-processing module that Some data goes in, and it comes out in a more useful form. layers extract representations out of the data fed into them. representations that are more meaningful for the problem at hand. Most of deep learning consists of chaining together simple layers that will implement a form of progressive data distillation. A deep-learning model is like a sieve for data processing,
made of a succession of increasingly refined data filtersthe layers.

To make the network ready for training, we need to pick three more things, as part of the compilation step:
1} A loss function — How the network will be able to measure its performance on the training data, and thus how it will  be able to steer itself in the right direction.
2} An optimizer — The mechanism through which the network will update itself based on the data it sees and its loss function.
3} Metrics to monitor during training and testing — Here, we’ll only care about accuracy (the fraction of the images that were correctly classified)

2.3. The compilation step

2.4. Preparing the image data
preprocess the data by reshaping it into the shape the network expects and scaling it so that all values are in the [0, 1] interval. our training images stored in an array of shape (60000, 28, 28) of type uint8 with values in the [0, 255] interval. transform it into a float32 array of shape (60000, 28 * 28) with values between 0 and 1.

2.5. Preparing the labels
categorically encode the labels

2.6. Fit the model 
Two quantities are displayed during training: the loss of the network over the training data, and the accuracy of the network over the training data.

In [1]:
################ 1. Loading the MNIST dataset in Keras #####################
from keras.datasets import mnist
from keras import models
from keras import layers
from keras.utils import to_categorical

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
# train_images.shape ### dimension of tesndor along with each axes in this case (60000, 28, 28)
# len(train_labels)
# train_labels
# test_labels
print(train_images.ndim) ### Display number of axes, in this case 3
# print(train_images.dtype) ### type of data conatain in tensor, in this case uint8

################ 2. The network architecture #####################
# network = models.Sequential()
# network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,))) 
# ### Dense layers are fully connected neural layers.
# network.add(layers.Dense(10, activation='softmax')) 
# ### 10-way softmax layer, i.e. it will return an array of 10 probability scores (summing to 1).
    
################ 3. The compilation step #########################

### To make the network ready for training, we need to pick three things, as part of the
### compilation step:
### 1) optimizer - mechanism through which the network will update itself based on the data it
###                sees and its loss function.
### 2) Loss function - the network will be able to measure its performance on the training data and 
###                   steer itself in the right direction.
### 3) Metrics ( to monitor during training and testing) - in this case only care about accuracy
###             i.e. the fraction of the images that were correctly classified

# network.compile(optimizer='rmsprop', 
#                   loss='categorical_crossentropy', 
#                   metrics=['accuracy']) 

################ 4. Preparing the image data #########################


### Transform training array into float32 array of shape (60000,28 *28) with values betn 0 and 1.
# train_images = train_images.reshape((60000, 28 * 28))
# train_images = train_images.astype('float32')/255

# test_images = test_images.reshape((10000, 28 * 28))
# test_images = test_images.astype('float32')/255

################ 5. Preparing the labels #########################

### categorically encode the labels
# train_labels = to_categorical(train_labels)
# test_labels = to_categorical(test_labels)

################ 6. Fit the model ##############################

# network.fit(train_images, train_labels, epochs=5, batch_size=128)

################ 7. check with Test Data ##############################

# test_loss, test_acc = network.evaluate(test_images, test_labels)
# print("Test Accu: ", test_acc) ### Test Accuracy: 0.9801

C:\Users\Satish\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


3


2.2.1 Scalars (0D tensors)

A tensor that contains only one number is called a scalar (or scalar tensor, or 0-dimensional
tensor, or 0D tensor). In Numpy, a float32 or float64 number is a scalar tensor (or scalar
array)You can display the number of axes of a Numpy tensor via the ndim attribute; a scalar
tensor has 0 axes (ndim == 0). The number of axes of a tensor is also called its rank.

2.2.2 Vectors (1D tensors)
An array of numbers is called a vector, or 1D tensor. A 1D tensor is said to have exactly
one axis. 

2.2.3 Matrices (2D tensors)
An array of vectors is a matrix, or 2D tensor. A matrix has two axes (often referred to rows and columns). The entries from the first axis are called the rows, and the entries from the second axis are called the columns. In the previous example, [5, 78, 2, 34, 0] is the first row of x, and [5, 6, 7] is the first column. 

2.2.4 3D tensors and higher-dimensional tensors
pack such matrices in a new array, you obtain a 3D tensor, which you can visuallyinterpret as a cube of numbers. 

2.2.5 Key attributes
A tensor is defined by three key attributes:
1} Number of axes (rank) -  3D tensor has three axes, and a matrix has two axes.
2} Shape - It's tuple of integers, how many dimension tesnsor has along each side.
3} Data type -  This is the type of the data contained in the tensor

    2.6 Displaying the fourth digit
    Display the fourth digit in this 3D tensor, using the library Matplotlib. .
     Vector data—2D tensors of shape (samples, features)
 Timeseries data or sequence data—3D tensors of shape (samples, timesteps,
features)
 Images —4D tensors of shape (samples, height, width, channels) or (samples,
channels, height, width)
 Video—5D tensors of shape (samples, frames, height, width, channels) or
(samples, frames, channels, height, width)
2.2.6 Manipulating tensors in Numpy
previous example, we selected a specific digit alongside the first axis using the syntax train_images[i]. Selecting specific elements in a tensor is called tensor slicing.

2.2.7 The Notation of data batches 
The first axis (axis 0, because indexing starts at 0) in all data tensors you’ll come across in deep learning will be the samples axis (sometimes called the samples dimension).
deep-learning models don’t process an entire dataset at once; rather, they break the data into small batches. example, one batch of our MNIST digits with batch size of 128. 
When considering such a batch tensor, the first axis (axis 0) is called the batch axis or
batch dimension. 

2.2.8 Real-world examples of data tensors

The data you’ll manipulate will almost always fall into one of the following categories.
1} Vector data—2D tensors of shape (samples, features)
2} Timeseries data or sequence data—3D tensors of shape (samples, timesteps,
features)
3} Images —4D tensors of shape (samples, height, width, channels) or (samples,
channels, height, width)
4} Video—5D tensors of shape (samples, frames, height, width, channels) or
(samples, frames, channels, height, width)

In [8]:
################ 2.1 Scalars (0D tensors) ##############################
import numpy as np

# x = np.array(12)
# x
# x.ndim ### Display number of axes, in this case 0
# x.shape ### tensor has none{()} dimensions
# x.dtype ### tensor contain int32 type data

################ 2.2 Vectors (1D tensors) ##############################

# x = np.array([1,3,7,11,15]) ### as vector has 5 element, then  it's 5 dimensional vector
# x
# x.ndim ### Display number of axes, in this case 1
# x.shape ### tensor has (5,) dimensions
# x.dtype ### tensor contain int32 type data

################ 2.3 Matrices (2D tensors) ##############################

# x  = np.array([[5, 78, 2, 34, 0],
#                [6, 79, 3, 35, 1],
#                [7, 80, 4, 36, 2]])
# x.ndim ### Display number of axes, in this case 2
# x.shape ### tensor has (3, 5) dimensions
# x.dtype ### tensor contain int32 type data

################ 2.4 3D tensors #########################################

# x = np.array([[ [5, 78, 2, 34, 0],
#                 [6, 79, 3, 35, 1],
#                 [7, 80, 4, 36, 2]],
#                [[5, 78, 2, 34, 0],
#                 [6, 79, 3, 35, 1],
#                 [7, 80, 4, 36, 2]],
#                [[5, 78, 2, 34, 0],
#                 [6, 79, 3, 35, 1],
#                 [7, 80, 4, 36, 2]]])
# x.ndim ### Display number of axes, in this case 3
# x.shape ### tensor has (3, 3, 5) dimensions
# x.dtype ### tensor contain int32 type data

################ 2.6 Displaying the fourth digit ##########################

### To display the fourth digit in 3D tensor, using Matplotlib library 
# digit = train_images[4]
# import matplotlib.pyplot as plt
# plt.imshow(digit, cmap=plt.cm.binary) 
# plt.show() 
#### Shows fourth sample from data set

################ 2.2.6 Manipulating tensors in Numpy ##########################

### selects digits #10 to #100 puts them in an array of shape(90, 28, 28)
### specifies a start index and stop index for the slice along each tensor axis.
# my_slice = train_images[10:100] 
# print(my_slice.shape)

### Slice the 3D tensor in from 10 to 25 (=15) first index
###                        from 2 to 12 (=10) second index i.e. rows
###                        from 3 to 17 (=14) third index i.e. columns
# my_slice = train_images[10:25, 2:12, 3:17] 
# print(my_slice.shape)

### select 14 × 14 pixels in the bottom-right corner of all images
# my_slice = train_images[:, 14:, 14:] 
# print(my_slice)

### To crop the images to patches of 14 × 14 pixels centered in the middle
# my_slice = train_images[:, 7: -7, 7: -7]
# print(my_slice)

################ 2.2.7 The Notation of data batches ##########################

# batch = train_images[:128] ### MNIST digits with batch size of 128
# print(batch)
# batch_2 = train_images[128:256] ### next batch
# batch_n = train_images[128 * n: 128 * (n+1)] ### nth batch



[[[240 253 253 ...   0   0   0]
  [ 45 186 253 ...   0   0   0]
  [  0  16  93 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[241 243 234 ...   0   0   0]
  [143  91  28 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 ...

 [[253 254 253 ...   0   0   0]
  [ 72 192 254 ...   0   0   0]
  [  0   6 242 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0  31 127 ...   0   0   0]
  [ 27 218 252 ...   0   0   0]
  [194 253 217 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0  

2.3 The gears of neural networks: tensor operations

We can network by stacking Dense layers on top of each other.

2.3.1 Element-wise operations

The relu and addition are element-wise operations i.e. operations that are applied independently to each entry in the tensors being considered. these operations are highly amenable to massively parallel implementations(vectorized implementations).

2.3.2 Broadcasting

when the shapes of the two tensors being added differ then the smaller tensor will be broadcasted to match the shape of the larger tensor.
Broadcasting consists of two steps
1} Axes (called broadcast axes) are added to the smaller tensor to match the ndim of
the larger tensor.
2} The smaller tensor is repeated alongside these new axes to match the full shape
of the larger tensor

2.3.3 Tensor dot

The dot operation, also called a tensor product is the most common, most useful tensor operation. Contrary to element-wise operations, it combines entries in the input tensors. An element-wise product is done with the * operator in Numpy, Keras, Theano, and TensorFlow. dot uses a different syntax in TensorFlow, but in both Numpy and Keras it’s done using the standard dot operator.

2.3.4 Tensor reshaping

Reshaping a tensor means rearranging its rows and columns to match a target shape. the reshaped tensor has the same total number of coefficients as the initial tensor. A special case of reshaping that’s commonly encountered is transposition. Transposing a matrix means exchanging its rows and its columns, so that x[i, :] becomes x[:, i].

2.3.5 Geometric interpretation of tensor operations

elementary geometric operations such as affine transformations, rotations, scaling, and so on can be expressed as tensor operations.

2.3.6 A geometric interpretation of deep learning



In [33]:
################ 2.3 neural networks: tensor operations ##########################
import keras
import numpy as np

### Below layer is function which take input as 2D tensor and returns another 2D tensor
# keras.layers.Dense(512, activation='relu')

### the is function where W is a 2D tensor and b is a vector, both attributes of the layer
### three tensor operations here: a dot product (dot) between the input tensor and a tensor 
### named W; an addition (+) between the resulting 2D tensor and a vector b; and, 
### finally, a relu operation. relu(x) is max(x, 0).
# output = relu(dot(w, input) + b)

################ 2.3.1 element-wise relu operation ##########################
# x  = np.array([[5, 78, 2, 34, 0],
#                [6, 79, 3, 35, 1],
#                [7, 80, 4, 36, 2]])
# y  = np.array([[15, 78, 28, 34, 20],
#                [61, 79, 33, 35, 13],
#                [73, 80, 64, 36, 29]])
# print(np.maximum((x - y), -1000.))  ### element-wise add/sub/mul in Numpy array
# print(x.shape)
# print(len(x.shape))
# def naive_relu(x):
#     assert len(x.shape) == 2  ### x is 2D Numpy tensor
#     x = x.copy()              ### avoid overwritting the input tensor
#     for i in range(x.shape[0]):
#         for j in range(x.shape[1]):
#             x[i, j] = max(x[i, j], 0)
#     return x        
# print(naive_relu(x))

################ 2.3.1 element-wise add/sub/mul operation ##########################
# def naive_add(x, y):
#     assert len(x.shape) == 2
#     assert x.shape == y.shape  ### x and y are 2D Numpy tensor
#     x = x.copy()               ### to avoid overwriting the input tensor
#     for i in range(x.shape[0]):
#         for j in range(x.shape[1]):
#             x[i, j] *= y[i, j] ### on the same principle, we can do element wise add/sub/mult
#     return x        
# print(naive_add(x, y))

################ 2.3.2 Broadcasting ##############################################

# x  = np.array([[5, 78, 2, 34, 0],
#                [6, 79, 3, 35, 1]])
# y  = np.array([15, 78, 28, 34, 20])
# len(x.shape)
# len(y.shape)

# def naive_add_matrix_and_vector(x, y):
#     assert len(x.shape) == 2       ### x is 2D Numpy tensor
#     assert len(y.shape) == 1       ### y is 1D Numpy vector
#     assert x.shape[1] == y.shape[0]
    
#     x = x.copy()                   ###  avoid rewritting the input tensor
#     for i in range(x.shape[0]):
#         for j in range(x.shape[1]):
#             x[i, j] *= y[j]        ### similarly, we can elemnt wise sub/mul tensor with vector
#     return x        
# print(naive_add_matrix_and_vector(x, y))    

################ 2.3.3 Tensor dot ##############################################
###### dot product of two vectors x and y.
# x  = np.array([5, 78, 2, 34, 24])
# y  = np.array([15, 78, 28, 34, 20])

# def naive_vector_dot(x, y):
#     assert len(x.shape) == 1
#     assert len(y.shape) == 1
#     assert x.shape[0] == y.shape[0]
#     z = 0
#     for i in range(x.shape[0]):
#         z += x[i] * y[i]
#     return z
# print(naive_vector_dot(x, y))

###### dot product of matrix x and vector y
# x  = np.array([[5, 78, 2, 34, 0 ],
#                [6, 79, 3, 35, 1]])
# y  = np.array([15, 78, 28, 34, 20])
# len(x.shape)
# len(y.shape)

# def naive_add_matrix_and_vector(x, y):
#     assert len(x.shape) == 2       ### x is 2D Numpy tensor
#     assert len(y.shape) == 1       ### y is 1D Numpy vector
#     assert x.shape[1] == y.shape[0]
    
#     z = np.zeros(x.shape[0])       ### vector of 0's with same shape of y
#     for i in range(x.shape[0]):
#         for j in range(x.shape[1]):
#              z[i] += x[i, j] * y[j]
#     return z        
# print(naive_add_matrix_and_vector(x, y))

###### dot product of matrix x(3, 5) and matrix y(5, 3)
# x  = np.array([[5, 78, 2, 34, 0],
#                [6, 79, 3, 35, 1],
#                [7, 80, 4, 36, 2]])
# y  = np.array([[15, 78, 28],
#                [34, 20, 61],
#                [79, 33, 35],
#                [13, 73, 80],
#                [64, 36, 29]])
# def naive_matrix_dot(x, y):
#     assert len(x.shape) == 2   ### x numpy matrix
#     assert len(y.shape) == 2   ### y numpy matrix
#     assert x.shape[1] == y.shape[0] ### 1st dimension of x must be same as 0th dimension of y
    
#     z = np.zeros((x.shape[0], y.shape[1])) ### matrix of 0 with 1st dimension of x and 2nd of y
#     for i in range(x.shape[0]):      ### iterate over x's rows
#         for j in range(y.shape[1]):  ### iterate over y's column
#             rows_x = x[i, :]
#             colums_y = y[:, j]
#             z[i, j] = naive_vector_dot(rows_x, colums_y)
#     return z
# print(naive_matrix_dot(x, y))


################ 2.3.4 Tensor reshaping ###########################################
# y  = np.array([[15, 78, 28],
#                [34, 20, 61],
#                [79, 33, 35],
#                [13, 73, 80],
#                [64, 36, 29]])
# # y.shape
y.reshape(15,1)
# x = np.array([[0., 1.],
#               [2., 3.],
#               [4., 5.]]) 
# x.shape
# x.reshape(2,3)
# x = np.zeros((300,20))
# x = np.transpose(x) ### Transposing a matrix means exchanging its rows and its columns
# x
# x.shape

array([[15],
       [78],
       [28],
       [34],
       [20],
       [61],
       [79],
       [33],
       [35],
       [13],
       [73],
       [80],
       [64],
       [36],
       [29]])

2.4 The engine of neural networks: Gradient-based optimization